import Carousel from '@/src/Carousel'
import Header from '@/src/Header'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Form Trip</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/FT-icon.ico" />
      </Head>
      <Header />
      <Carousel />
    </>
  )
}
